### ISSUE TITLE
Passing in --token for CD

### ISSUE THREAD

**Issue by janat08** [jkrup/meteor-now#107]
**Is your feature request related to a problem? Please describe.**
Can't set up CD

**Describe the solution you'd like**
passing unrecognized parameters to now-cli

**Describe alternatives you've considered**
non

**Additional context**
trying to setup gitlab Continuous Delivery on the shared runners (public resources)

**Comment by lmachens** [comment]
Same issue here. Looks like it is not possible to pass now options at all. 
Other examples are `--regions` or `--force`.

Maybe we should add an option like `--now-options` which could be used to bypass options to the now process.
So it would be possible to call `meteor-now --now-options="--token xyz --regions sfo"`.
What do you think @jkrup ?

**Comment by lmachens** [comment]
Seems like it should already work if I take a look at https://github.com/jkrup/meteor-now/blob/8533f05ceff4f1fe5142137d6a63246377903e61/src/api/args.js#L53

**Comment by janat08** [comment]
I suppose this is fixed
