### ISSUE TITLE
 ▲ The built image size (417.0M) exceeds the 100MiB limit

### ISSUE THREAD

**Issue by ninjaPixel** [jkrup/meteor-now#120]
**Describe the bug**
The deploy fails because the image is too big. The error message is:

```
 ▲ The built image size (417.0M) exceeds the 100MiB limit
```

**To Reproduce**
Create a boilerplate meteor app and try to deploy:

1. `meteor create simple-todos`
2. `cd simple-todos`
3. `meteor npm i`
4. `now login`
5. `meteor-now --public`

Note that if I pass a mongo URL, the image size is about 100M smaller, but the deploy still fails.

**Expected behavior**
The app is deployed to Now

**Desktop **
 - OS: OS X
 - Node: 8.11.3
 - NPM 6.4.0
- meteor-now 0.6.2 (I also tried 0.6.1)
- now 11.3.10

**Additional context**
Not sure if it's a red herring, but I also see the following NPM warning:

```
Step 11/19 : RUN npm install
>  ---> Running in 8046652cd477
> 
> fibers@2.0.0 install /usr/src/app/bundle/programs/server/node_modules/fibers
> node build.js || nodejs build.js
> 
> `linux-x64-57` exists; testing
> Binary is fine; exiting
> npm WARN lifecycle meteor-dev-bundle@~install: cannot run in wd %s %s (wd=%s) meteor-dev-bundle@ node npm-rebuild.js /usr/src/app/bundle/programs/server
> npm notice created a lockfile as package-lock.json. You should commit this file.
> added 130 packages in 5.308s
```

I've tried changing the base image to `node:alpine` as per [this issue](https://github.com/zeit/now-cli/issues/1523) but the build failed at step 5.

**Comment by brianmcdonough** [comment]
I have the same issue: The built image size (346.2M) exceeds the 100MiB limit

My app is 84 MB locally. Is the issue caused by meteor-now or is the app somehow growing 268 MB once it gets to Zeit's servers?

Here's more on the reason for the change on zeit: this issue https://github.com/zeit/now-cli/issues/1523

**Comment by evolross** [comment]
Does the bundle-splitting of 1MB for the free ZEIT plan need to be used to split files into 100MB chunks for the paid ZEIT plan?  Is there some limit on ZEIT of 100MB per file upload?

**Comment by brianmcdonough** [comment]
Zeit made an improvement that requires under 100MB to deploy to cloud version 2, which they made standard for all deployments. Deploying to cloud: 'v1' still allows larger file sizes.

     "features": {
        "cloud": "v1"
      },

A quick solution to the current issue in meteor-now would be to change the setting. 

I can try to do it by pull request, but it could take a while as I'm unfamiliar with the code.

**Comment by qualitymanifest** [comment]
@brianmcdonough have you had success deploying to cloud v1 using meteor-now? If so, how did you go about it? I was actually just writing https://github.com/jkrup/meteor-now/issues/121 when you posted that. I've tried several ways and I can't get it to work.

**Comment by brianmcdonough** [comment]
I think it would need to be an option made available in the deployment string of meteor-now. Either that or baked into the deployment as the only option. 

Still working out the details, but will post an update with any progress

**Comment by brianmcdonough** [comment]
@jkrup Here's what I've tried:

Add the following code to packages.json (per zeit now docs):
       "now": {
         "features": {
             "cloud": "v1"
         }
       }

Add `"'features': { 'cloud': 'v1' }"` to a secret on now, then include it as `@cloud-settings in meteor-now deployment string

Add `"'features': { 'cloud': 'v1' }"` to the end of the meteor now deployment string on its own. The meteor now codebase seems to accommodate  `remainingVariables` but not sure how this fits in, or what use case `remainingVariables` would cover.

None of the above works, but I'll keep working on it until something breaks through as I need it to work yesterday for a customer.

I'm currently looking into how the `now.features.cloud` version could be integrated into the deployment string as an additional env variable. 

I thought the above information might be helpful in identifying the first order issue. I'll let you know if I'm able to develop a solution that works on my own through pull-request.

**Comment by jkrup** [comment]
I've attempted to reduce build sizes with node alpine, but especially for apps bundled with mongodb that may be very tricky (or not possible). So for now I'll quickly push an update as per @brianmcdonough 's comment to add a `now.json` with `"'features': { 'cloud': 'v1' }"`

**Comment by jkrup** [comment]
Everyone having this issue please try `npm install meteor-now@beta` and then redeploying using `meteor-now`

**Comment by qualitymanifest** [comment]
`Success! Deployment ready`
Thank you @jkrup !

**Comment by jkrup** [comment]
#123

**Comment by brianmcdonough** [comment]
Even with the update to 0.7.0 I'm still getting the same error when I try to deploy:

` meteor-now -e METEOR_SETTINGS=@common-settings -e ROOT_URL=https://www.common.cx  -e MONGO_URL=@common-db
⠀⢘ [METEOR-NOW] - Building meteor app (this can take several minutes) Node#moveTo was deprecated. Use Container#append.
✔ [METEOR-NOW] - Building meteor app (this can take several minutes) 
✔ [METEOR-NOW] - Preparing build 
⢀⠀ [METEOR-NOW] - Deploying build (this can take several minutes) args are  { _:
   [ '/usr/local/Cellar/node/10.4.1/bin/node',
     '/usr/local/bin/meteor-now' ],
  help: false,
  version: false,
  e:
   [ 'METEOR_SETTINGS=@common-settings',
     'ROOT_URL=https://www.common.cx',
     'MONGO_URL=@common-db' ],
  '$0': '/usr/local/bin/meteor-now' }
> Upload [==========----------] 50% 12.7s (65.9MB) [70 files]⡋⠀ [METEOR-NOW] - Deploying build ⡋⢀ [METEOR-NOW] - Deploying build (this can take several minutes) > Upload [=================--> Upload [===================-] 94% 1.8s (65.9MB) [70 files]⡋⠁ [METEOR-NOW] - Deploying build (✔ [METEOR-NOW] - Deploying build (this can take several minutes) 
✔ [METEOR-NOW] - App url is https://common-julftpxdwn.now.sh 
> Building…
> Sending build context to Docker daemon  69.17MB
> Step 1/11 : FROM node:8.9.4
>  ---> 672002a50a0b
> Step 2/11 : LABEL name="common"
>  ---> Running in a87aad79776c
> Removing intermediate container a87aad79776c
>  ---> 2e46a2adc973
> Step 3/11 : COPY . /usr/src/app/
>  ---> ee66eb40c28c
> Step 4/11 : WORKDIR /usr/src/app
> Removing intermediate container b7b6071791cf
>  ---> c6a4f27b420c
> Step 5/11 : RUN cat *sf-part* > bundle.tar.gz
>  ---> Running in 6a6e15a430a3
> Removing intermediate container 6a6e15a430a3
>  ---> e0d1d8ca8cfa
> Step 6/11 : RUN tar -xzf bundle.tar.gz
>  ---> Running in 67c1d808cb75
> Removing intermediate container 67c1d808cb75
>  ---> 699d4b6613d7
> Step 7/11 : WORKDIR bundle/programs/server
> Removing intermediate container 33f18a9e9183
>  ---> 14db0d8d27cc
> Step 8/11 : RUN npm install
>  ---> Running in 2a9086cd769a
> 
> fibers@2.0.0 install /usr/src/app/bundle/programs/server/node_modules/fibers
> node build.js || nodejs build.js
> 
> `linux-x64-57` exists; testing
> Binary is fine; exiting
> npm WARN lifecycle meteor-dev-bundle@~install: cannot run in wd %s %s (wd=%s) meteor-dev-bundle@ node npm-rebuild.js /usr/src/app/bundle/programs/server
> added 131 packages in 2.555s
> Removing intermediate container 2a9086cd769a
>  ---> 6a23ff1ab23f
> Step 9/11 : WORKDIR ../../
> Removing intermediate container db66680c3e57
>  ---> d6a6a490271d
> Step 10/11 : EXPOSE 3000
>  ---> Running in 55e1b014dadf
> Removing intermediate container 55e1b014dadf
>  ---> 1b9770fc7c7c
> Step 11/11 : CMD ["node", "main.js"]
>  ---> Running in 4580215a20b4
> Removing intermediate container 4580215a20b4
>  ---> e7a5b9d07d1e
> Successfully built e7a5b9d07d1e
> Successfully tagged build:weFsyyihCEGCIcQQYVadSWNB_1535051721
> ▲ Assembling image
> ▲ The built image size (482.1M) exceeds the 100MiB limit
> Error! Build failed`
