### ISSUE TITLE
Does meteor-now support now settings in now.json or package.json?

### ISSUE THREAD

**Issue by qualitymanifest** [jkrup/meteor-now#121]
**Describe the bug**

Now settings in `now.json` or `package.json` don't appear to have an effect. I am trying to use Now cloud v1 so that I can continue to deploy my app until the option for multistage builds is available. I have tried a few different ways, but keep getting

> The built image size (328.0M) exceeds the 100MiB limit

which tells me that now is not receiving those settings.

**To Reproduce**

1. Add the following to package.json:
```
"now": {
  "features": {
    "cloud": "v1"
  }
}
```
2. Deploy as usual: `meteor-now -e MONGO_URL=mongodb://etc -e ROOT_URL=https://etc --public`

**OR**

1. Create a now.json in the project root with the following:
```
{
  "features": {
     "cloud": "v1"
  }
}
```
2. Deploy as usual: `meteor-now -e MONGO_URL=mongodb://etc -e ROOT_URL=https://etc --public`
2b. Also try using `--local-config` flag to point to now.json (probably isn't necessary since it's at the project's root)

**Expected behavior**

Cloud v1 is used, app deploys successfully.

**Desktop (please complete the following information):**

 - OS: Linux mint 18
 - meteor-now: 0.6.1
 - now: 11.3.12

**Additional context**

I also, separately from the above, tried removing my `--public` flag and adding `"public": true` to my now settings in now.json or package.json, just to see if that setting was recognized, and it is not.

Even once multistage builds are available, it seems that being able to pass now settings this way is still useful, since there are more options available than there are via the command line.

**Comment by jkrup** [comment]
I've hardcoded a minimal `now.json` to solve the main issue (>100MB): #123 , but I will start a PR to support a custom `now.json` for the other useful settings.

**Comment by LDubya** [comment]
It would be great if we could specify the monogo URL inside of now.json like they recommend in their official docs

That way we can just do `meteor-now` without having to paste in the MONGO_URL

**Comment by dnszero** [comment]
@LDubya Just in case it helps you, the way I handle MONGO_URL is with now secrets (https://zeit.co/docs/v1/features/env-and-secrets) and a package.json deploy script:
```
{
  "scripts": {
    "deploy": "meteor-now -e MONGO_URL=@my-mongo-url -e MAIL_URL=@my-mail-url -e ROOT_URL=https://cool.example.com -e NODE_ENV=production"
  },
}
```

When it's time to deploy I just `npm run deploy` and then manually update the now alias. 

No issues with cut-n-paste strings and nothing sensitive checked in to version control.

**Comment by LDubya** [comment]
@dnszero this has revolutionized my life. Thank you for this.

**Comment by qualitymanifest** [comment]
Closing this, since it looks like it was addressed in https://github.com/jkrup/meteor-now/pull/134
