### ISSUE TITLE
[FAQ] Will this work with any CI?

### ISSUE THREAD

**Issue by Sburke0708** [jkrup/meteor-now#129]
I'm interested in Circle CI or Travis CI. Will this work in tandem with any CI tools?

**Comment by jkrup** [comment]
In theory if you're able to set up your credentials for `now` on CI, then `meteor-now` should work as well. The only other dependency would be that your build server would need to also have `meteor` installed to run the `meteor build` command. 

https://zeit.co/docs/continuous-integration/travis
