### ISSUE TITLE
The property `features` is not allowed in now.json

### ISSUE THREAD

**Issue by developeron29** [jkrup/meteor-now#136]
**Describe the bug**
After running meteor-now
Getting this error
Error! The property `features` is not allowed in now.json when using Now 2.0 – please remove it.
while i don't have a now.json at all! and credentials are getting saved in ~/.now
![screen shot 2018-12-17 at 8 14 17 pm](https://user-images.githubusercontent.com/4932001/50071943-5fc9de00-0238-11e9-9b17-d121b6036669.png)

**To Reproduce**
> now login 
..✔ Confirmed email address!
> meteor-now 
... Something went wrong! ....

**Expected behavior**
should deploy successfully

**Comment by qualitymanifest** [comment]
@developeron29 

Go to https://zeit.co/account and log in
Select *v1* under *platform version* and hit *save*
Try to deploy again, it should work. Please let us know how it goes.

**Comment by developeron29** [comment]
Fixed, Thanks

**Comment by medied** [comment]
@qualitymanifest @developeron29 I'm running into the exact same issue but the following what I see in zeit.co/account under 'Platform Version'. Any insight? Thanks!

![image](https://user-images.githubusercontent.com/4752599/51359222-c25f0580-1a94-11e9-9483-01bc59c791a2.png)

**Comment by medied** [comment]
Seeing these threads now:

https://forums.meteor.com/t/deploy-to-zeit-meteor-now-deployment-basics/46650/3
https://github.com/jkrup/meteor-now/issues/121

**Comment by gringolalia** [comment]
I am not seeing «platform version» under `zeit.co/account` after logging in.

**Comment by chuckcarpenter** [comment]
@gringolalia check this comment, https://github.com/jkrup/meteor-now/issues/136#issuecomment-455392113

**Comment by archived-aft-bogus-german-visa-rejectio** [comment]
?????

**Comment by archived-aft-bogus-german-visa-rejectio** [comment]
so no longer supported for v1?
