### ISSUE TITLE
Alias Support not workinb

### ISSUE THREAD

**Issue by wortkotze** [jkrup/meteor-now#137]
**Describe the bug**
--alias command is not working 
--now-CLI is downgraded (newer version available)

**To Reproduce**
1. make Deployment with --alias comand
alias will not be applied to deployment

**Expected behavior**
alias settings from Comandline or from package.json/now.json will be added to deployment

**Additional context**
Newer Now.CLi is available by install from meteor-now 0.7 now-cli will be downgraded

thx for this great tool

**Comment by jkrup** [comment]
#139 / #119 should resolve this. Please try `npm install -g meteor-now@latest`
