### ISSUE TITLE
Meteor-Now swallow now output

### ISSUE THREAD

**Issue by vladejs** [jkrup/meteor-now#34]
When deploying an app, I can't see the generated URL for the deployment:
```
✔ [METEOR-NOW] - building meteor app
✔ [METEOR-NOW] - preparing build
✔ [METEOR-NOW] - deploying build
✔ [METEOR-NOW] - meteor app deployed to > NOTE: Overriding duplicate env key "PORT"

```

**Comment by purplecones** [comment]
Looks like the latest `now` cli changed its behavior in how it returns the deployed url. Will take a look.

In the meantime, you can just run `now ls` and it will display the urls of your deployed apps.
