### ISSUE TITLE
Could I remote to Mongo Port on Development?

### ISSUE THREAD

**Issue by thearabbit** [jkrup/meteor-now#37]
Could I remote to Mongo Port on Development?
Please help m.

**Comment by jkrup** [comment]
Hey, apologies if I'm mis-understanding, but is it that you want to connect directly to the MongoDB instance that we bundle (if you didn't specify your own mongo url)?

Unfortunately `now.sh` seems to firewall all ports except for one (which ever port is `EXPOSE`d by the Dockerfile. So there's no way to directly shell into the bundled MongoDB instance. But you can set up (and point to) a free separate MongoDB instance with a service like mlab.com

**Comment by thearabbit** [comment]
OK, thanks for your reply.
