### ISSUE TITLE
[Question] Is this compatible with version 1.2.1 of meteor?

### ISSUE THREAD

**Issue by johhansantana** [jkrup/meteor-now#41]
I'm trying to deploy a meteor app version 1.2.1 but when it finish deploying and go to the url it just stays there loading and sometimes it gives me 502 error.

`meteor-now -e MONGO_URL=mongodb://... -e MAIL_URL=smtp://... -e NODE_ENV=production`

**Note** 
I didn't specify a `ROOT_URL`  as I don't have a custom domain

**Comment by purplecones** [comment]
Hi @johhansantana, can you deploy with `-d` flag and forward us the output?

**Comment by johhansantana** [comment]
Sure @purplecones 

```
$ meteor-now -e MONGO_URL=mongodb://... -e MAIL_URL=smtp://... -e NODE_ENV=production -d
[METEOR-NOW] - running command: meteor build .meteor/local/builds  --architecture=os.linux.x86_64
[METEOR-NOW] - creating Dockerfile            
[METEOR-NOW] - splitting bundle
[METEOR-NOW] - looking for meteor settings file production.settings.json in root of project
[METEOR-NOW] - could not read production.settings.json
[METEOR-NOW] - no settings file found
[METEOR-NOW] - running command: cd .meteor/local/builds && now -e PORT=3000  -e ROOT_URL=http://localhost.com -e MONGO_URL=mongodb://... -e MAIL_URL=smtp://... -e NODE_ENV=production -d 
> Deploying ~/path/to/app/.meteor/local/builds
> [debug] `Dockerfile` found, assuming `deploymentType` = `docker`
> [debug] locating files /path/to/app/.meteor/local/builds: 7.485ms
> [debug] Getting files: 16.676ms
> [debug] Computing hashes: 158.768ms
> [debug] /now/create: 1430.832ms
> Ready! https://example-jsbzxietoa.now.sh (copied to clipboard) [2s]
> [debug] Will upload 14 files in 2 steps of 10 uploads.
> Upload [====================] 100% 0.0s
> Sync complete (12.44MB) [42s] 
> Initializing…
> [debug] closing agent
> Building
> ▲ docker build
> Removing intermediate container 9c1b700376a3
> Step 10 : EXPOSE 3000
>  ---> Running in ba0ec7211601
>  ---> 441604a22373
> Removing intermediate container ba0ec7211601
> Step 11 : CMD node main.js
>  ---> Running in 9518d60bb4cb
>  ---> f4eba08cce4c
> Removing intermediate container 9518d60bb4cb
> Successfully built f4eba08cce4c
> ▲ Storing image
> ▲ Deploying image
> ▲ Container started
```

there are a few other Docker logs but they seem to be scrolling on their own `iframe` for some reason after `docker build` there were more steps but could only copy from `step 10`

**Comment by johhansantana** [comment]
Here's a gif with the docker logs
![dockerlogs](https://cloud.githubusercontent.com/assets/9933887/24769172/7a233218-1ad3-11e7-8bc4-e58b4e7f16ad.gif)

**Comment by johhansantana** [comment]
Hmm this is weird, I just tried deploying another app which has v1.2.1 as well installed but this one has `METEOR@1.2.2-faster-rebuilds.0` and it worked. I'm going to try updating the other one to the same version and see if something changes.

**Comment by purplecones** [comment]
Try https://github.com/jkrup/meteor-now/issues/42 for logging.

I just deployed a `1.4.3.2` app without issues. We also initially did some tests with early meteor versions prior to `1.2` and it worked. Will check exactly `1.2.1` later.
