### ISSUE TITLE
Error 502 : An error occured with your deployment.

### ISSUE THREAD

**Issue by UShan89** [jkrup/meteor-now#43]
I get this error for my meteor app. 

I am trying to deploy the to-do example app. Is there a way to fix this?

**Comment by UShan89** [comment]
Never mind, it's my password complexity. Characters I copy paste and store else where get url encoded.

**Comment by jkrup** [comment]
Ah, I've experienced that issue before. It may be useful to use now `secrets` to store complex passwords

**Comment by UShan89** [comment]
makes sense @jkrup. That's a useful tip. However, I have never come across a good example. Can you help me use secrets and point me in that direction. I have seen this in the README too but have not yet figured out how to use secrets

**Comment by acomito** [comment]
@UShan89 I'm running into this problem with my AWS S3 keys stored in my settings.json... did you have the steps to do this? I'm using https://atmospherejs.com/edgee/slingshot so I need the keys named specifically in the settings.json

**Comment by christophmayrhofer** [comment]
@acomito I have the same problem with my aws keys in the settings. Have you found a solution?

**Comment by acomito** [comment]
@christophmayrhofer 

Did you make sure you have your settings in a file called production.settings.json? I think it needs to be in there specifically. Then it should pick it up and work like usual.
