### ISSUE TITLE
[?] Does meteor-now always compresses the files up to 1mb even if the account is pro?

### ISSUE THREAD

**Issue by vladejs** [jkrup/meteor-now#44]
Or it detects the account type and compresses the files accordingly?

I ask because my deployments are getting too slow to finish on `METEOR-NOW] - deploying build (this can take several minutes)` step

**Comment by purplecones** [comment]
Yea it does. Try deploying with the -d flag to see which step takes the most time. It might not be the split/combine step.

**Comment by vladejs** [comment]
It's actually getting slow when splitted files are been uploaded. I know, I have a slow (not that slow) Internet connection.

I see the compressed parts are in `tar.gz` format. It is well known that `7z` format compresses 2 or 3 times more, so my suggestion is to split and use `7z` instead. 

pd: `7z` also comes with great benefit: it understand symlinks.

**Comment by UShan89** [comment]
@vladejs meteor-now uses meteor's building option. 
[Here is some docs on it](https://guide.meteor.com/build-tool.html#compiles-with-build-plugins)

**Comment by UShan89** [comment]
@vladejs for fastest builds and compressions, 

You can create a Dockerfile :). Ultimately, now is a dockerized environment. Giving a dockerfile makes your life easy as hell

**Comment by vladejs** [comment]
@UShan89 , I mean that, process should be faster if by default it compresses files on `7z`. My wish is to have this feature natively on `meteor-now`

**Comment by purplecones** [comment]
@vladejs are you saying that your upload is significantly faster when uploading a single 5mb file versus uploading 10 files that are 0.5mb in size?

**Comment by vladejs** [comment]
no, i am saying that compressing files using 7z format you will get half
size when compressing, meaning that if now you get 10 files of 0.5 mb each,
when compressed in 7z you'll get 5 files of 0.3 mb each, saving huge
bandwith.

2017-04-24 11:27 GMT-04:00 Mirza Joldic <notifications@github.com>:

**Comment by vladejs** [comment]
I see, you're right, but, there is a way for meteor-now to do it:

The goal is to upload the project to now service fast, and have their
servers take care of the whole build process, so, my recommendation is to:

1. Instead of calling `meteor build`, compress the source project instead
(even without node_modules folder) and call now on it with the Dockerfile.
2. Have instructions on the Docker file to uncomppress the project, do an
npm install on it, then install meteor and run meteor build to get the
nodejs app.

This way we left the heavy lifting to now service and deployments get fast.

This image could help https://github.com/XervoIO/docker-build-meteor

2017-04-24 11:55 GMT-04:00 Sai Uday Shankar Korlimarla <
notifications@github.com>:

**Comment by jkrup** [comment]
We now allow for the `--nosplit` param to be passed in as `meteor-now --nosplit` #81
