### ISSUE TITLE
-e command not found

### ISSUE THREAD

**Issue by UShan89** [jkrup/meteor-now#45]
I have been successful to use -e and pass args earlier. 

Currently, I get an `-bash: -e: command not found` 

Need help in knowing what is going wrong here

**Comment by jkrup** [comment]
Could you post the full command? (feel free to obfuscate with `*****` any sensitive information)

**Comment by UShan89** [comment]
`meteor-now -d -e MONGO_URL=mongodb://user:password_21_chars_long@mymongodbalias:27107/dbname?readPreference=primary&ssl=true -e ROOT_URL=https://mydomain.net -e NODE_ENV=production`

I have filled in characters to show almost the exact command I use. The mongo settings and other settings work fine for me with localhost i.e. the database is working and accepts SSL only connections.  However, when I deploy, deploy is successful, from the deploy log. 

- Idea1
Modify the Dockerfile generated to suit my exact needs and use now directly but I have not yet tried this.

**Comment by UShan89** [comment]
@jkrup I see these issues happening only when I specify a mongo_url option. If I default to using the container provided mongo, all works fine. However, I need to use my mongo server and not the container one.

**Comment by UShan89** [comment]
@jkrup reinstalling meteor-now fixed my problem.

> magical harry potter stuff! This now leaves me confused**

**Comment by UShan89** [comment]
@jkrup All this happened because meteor does not care about self-signed certificate. Node rejects a self-signed certificate
