### ISSUE TITLE
possible to deploy to push updates to existing deployment?

### ISSUE THREAD

**Issue by acomito** [jkrup/meteor-now#48]
is there a command to update an existing deployment? Or do you just deploy to a new deployment/url. Then re-alias that new deployment/url. Then delete the old deployment/url?

**Comment by purplecones** [comment]
Your examples are accurate. That is how I deploy apps using now. Deployments are immutable so you cannot change or update an existing one. You can only delete it.

**Comment by acomito** [comment]
okay thanks for heads up
