### ISSUE TITLE
use local now instead of global now

### ISSUE THREAD

**Issue by purplecones** [jkrup/meteor-now#5]
user might not have now installed globally

**Comment by purplecones** [comment]
users will have to install `now` separately for `meteor-now` to work. We can provide a warning if it's not installed.

**Comment by mazlix** [comment]
#17 is a start by just manually calling it.. probably would be best if we can just call the javascript though instead of invoking now through shell/bash at all.

**Comment by purplecones** [comment]
I think its much easier and cleaner to use their cli and just invoke it the way we have been doing so far. Do you see any benefits in using their api instead?
