### ISSUE TITLE
Setting ROOT_URL with non-custom domain?

### ISSUE THREAD

**Issue by WWT2012** [jkrup/meteor-now#51]
Recently i want to implement a email verification function to my app
which is making use of `Meteor.absoluteUrl` and `ROOT_URL`
i am using the OSS plan with non-custom domains.
Any recommendation would be appreciated!

**Comment by jkrup** [comment]
One option you can do is have a Meteor.method (you'll probably want to password protect this method) that sets `process.ENV.ROOT_URL = ` whatever you pass in something like:

**Comment by jkrup** [comment]
Then you'll need to manually call `Meteor.call('somelongsecretcode', ' http://iw0e8fh9asdhf.now.sh')`, but that should work.

**Comment by acomito** [comment]
thanks @jkrup
