### ISSUE TITLE
absolute URL/Root URL with apollo app using meteor-now

### ISSUE THREAD

**Issue by acomito** [jkrup/meteor-now#53]
Apollo-Client needs to know the url endpoint to hit. When I dont have a custom domain, I've been setting arbitrary ROOT_URLs. Arbitrary URLs worked fine with meteor apps, but apollo uses the ROOT_URL to connect (or you can give it a uri) but in both cases I have no idea what the URL will be until after the app is deployed. Is there anyway around this without using a custom domain?

Maybe I can run a method on startup to grab this.connection uri and reset the environment variable ROOT_URL?

or maybe vanilla js: window.location.hostname on client

**Comment by purplecones** [comment]
Have you tried aliasing the deployment to a *.now.sh URL and using that as the root URL?

-
MJ

**Comment by jkrup** [comment]
Yeah #51 explains a possible workaround: you could do something to the effect of

```
Meteor.methods({
  setRootUrl: (pass, url) {
    if (pass === 'somelongsecretcode') {
      process.env.ROOT_URL = url;
    }
  },
});
```

Then you'll need to manually call Meteor.call('somelongsecretcode', ' http://iw0e8fh9asdhf.now.sh'), but that should work.
