### ISSUE TITLE
The System Cannot Find The File Specified

### ISSUE THREAD

**Issue by jamiebones** [jkrup/meteor-now#54]
Hello please i am trying to upload a meteor app using this command meteor-now mongodb://<username>:<password>@hhdhdh/dbase -e NODE_ENV=production but i keep getting the The System Cannot Find The File Specified. But using meteor-now everything works fine. I am on windows 10. Thank you

**Comment by jkrup** [comment]
The proper command for using a MONGO_URL would be `meteor-now -e MONGO_URL=mongodb://... -e NODE_ENV=production` (notice the `-e MONGO_URL` ... I'm not sure but it's also possible that the `-e NODE_ENV=production` is causing it to look for a file named `production.settings.json` (if you're not using `Meteor.settings` then you could just try `echo "{}" > production.settings.json` and then re-run).

Please let me know if either of those fixes the issue.

**Comment by jamiebones** [comment]
I have used the right syntax as you have specified but it still gives me an error  meteor-now -e MONGO_URL=mongodb://<>:<password>@------ -e NODE_ENV=production -d but the error is still the same. I noticed that the error is caused by the MONGO_URL property . It works fine with the NODE_ENV. Thanks

**Comment by jkrup** [comment]
Sometime weird behaviour occurs with special characters, maybe try saving the entire `MONGO_URL` as a `now secret` (`now secrets add mongourl 'mongodb://<>:@-----'`) and then deploy with `meteor-now -e MONGO_URL=@mongourl ...`
