### ISSUE TITLE
Automate alias for new deployed instances

### ISSUE THREAD

**Issue by tomyo** [jkrup/meteor-now#59]
Hi, awesome work!
Is there a way to automate alias rename after deploy is completed?
If not, would be great te be able to call `meteor-now (...) alias=<project-url>`
which would call `now alias <new-deploy-id> <project-url>` after deploy is complete.

What I want to accomplish is one-call-deploy, without having to scroll in the console, find the new url, and call now alias.

Thanks!

**Comment by alexpriceonline** [comment]
@tomyo I use a bash script for this

```
#!/bin/sh
meteor-now -e 'NODE_ENV=production'
now alias
```

Make sure to have something like this in your `package.json`:

```
  "now": {
    "name": "app",
    "alias": "my-domain.com",
  },
```

Checkout the [docs](https://zeit.co/docs/features/configuration) for more

**Comment by c316** [comment]
I'm using meteor-now and CircleCI to do continuous deployments and I'm not able to just use a script or run the `now alias` command because meteor-now uses the folder name as the now name. This means that if I want to be able to do a production and a dev deployment then both of these will be deployed to now under the same name.

**Comment by AshHimself** [comment]
Sound like a PR @c316 do pass a param which will be used for the alias. I for one would like to do this as well as i'm currently assigning alias manually.

**Comment by c316** [comment]
@jkrup do you think you'd merge a pull request with this switch added? If so, I'll work on one.

**Comment by jkrup** [comment]
Yeah @c316 I think it would be a great addition! Thanks!

**Comment by c316** [comment]
@jkrup ok, here it is https://github.com/jkrup/meteor-now/pull/119

**Comment by Sburke0708** [comment]
@jkrup can you merge this? <3

**Comment by c316** [comment]
I think this can be closed @jkrup since this is now merged, right?

**Comment by jkrup** [comment]
Yup! Thanks!
