### ISSUE TITLE
externalize Dockfile contents?

### ISSUE THREAD

**Issue by purplecones** [jkrup/meteor-now#6]

**Comment by purplecones** [comment]
Provide ability to override default Dockerfile with a user provided one? Perhaps we can look for a Dockerfile in the Meteor dir and use that if it exists, otherwise use the our default one.

**Comment by purplecones** [comment]
This just provides additional complexity thats not necessary. Either way, the process needs our custom Dockerfile to properly run on the free plan. Closing issue. We can explore down the road again.

**Comment by emilbruckner** [comment]
I love meteor-now, but can't use it with one app, which needs Imagemagick and some other node version
Support for a custom Dockerfile would be highly appreciated
The splitting is a good hack, so without adding much complexity, I could also think of adding flags for choosing a node version and adding Imagemagick (I don't know how frequently it is used, but there are Images on Docker Hub supporting it)
But copying and editing a Dockerfile also isn't too hard …

**Comment by mazlix** [comment]
@emilbruckner good to know, we could look into allowing a custom Dockerfile.

For now it's definitely not hard for us to allow specifying NODE. Could you give me some details about what your using for imagemagick? 

Do you know if all you'd need in the dockerfile is a `RUN apt-get install imagemagick`? If so maybe we could support passing in a list of packages which we would run `apt-get install` in?

**Comment by emilbruckner** [comment]
I use `meteor/cfs:graphicsmagick` for Imagemagick. `RUN apt-get install imagemagick`does what I need. Passing in a list sounds like an option, but I don't know what others would use it for …

**Comment by mazlix** [comment]
Hey @emilbruckner you should be able to run `meteor-now --dependencies imagemagick` and deploy your app with meteor-now. Please let me know if that's working for you. (You will need to `npm install -g meteor-now@0.1.2` first)

**Comment by emilbruckner** [comment]
@mazlix yes, works perfectly! thanks

**Comment by alimgafar** [comment]
Is this still an open issue? @jkrup @purplecones

**Comment by vladejs** [comment]
What about globally installed npm modules? 

My use case is `phantomjs`, which is used by `html-pdf` library which assumes phantomjs is installed globally. 

I don't know how to instruct the docker file to `npm i -g phantomjs`
