### ISSUE TITLE
Providing only METEOR_SETTINGS should be enough to do a proper deploy

### ISSUE THREAD

**Issue by tomyo** [jkrup/meteor-now#60]
Hi again!
If all the environment variables I use are in a settings.json file, would be great to only set the NODE_ENV, and let now or meteor-now to automatically set the variables in the file.
Or, from local settings.json file, when I call `meteor-now -e METEOR_SETTINGS=settings.json`

Currently, I'm forced to repeat some values from meteor settings, like MONGO_URL, if the change, I have to updated in two places.

This is how I do it now, in a `deploy.sh` file:
```
ROOT_URL="$(cat production.settings.json | jq '.ROOT_URL')"
MAIL_URL="$(cat production.settings.json | jq '.MAIL_URL')"
MONGO_URL="$(cat production.settings.json | jq '.MONGO_URL')"
NODE_ENV="$(cat production.settings.json | jq '.NODE_ENV')"
meteor-now -d -e NODE_ENV=$NODE_ENV -e MONGO_URL=$MONGO_URL -e ROOT_URL=$ROOT_URL -e MAIL_URL=$MAIL_URL
```

Thanks.

**Comment by andruschka** [comment]
This is something meteor-now hast nothing to do with. Meteor environment variables does not belong into the settings.json file.
