### ISSUE TITLE
app names being created with quotes as part of the name.

### ISSUE THREAD

**Issue by 1jerry** [jkrup/meteor-now#61]
## Problem:
because of a[ bug](https://github.com/joyent/node-docker-file-parser/pull/3) in Docker, your Dockerfile is not being parsed correctly and the quote marks are part of the name that _now_ is giving to the application.
## Clues:
If I am in my application directory named "bob" and run meteor-now --public I get a new instance created by _now_.  When I list using _now_ I can see it:
> $now ls
x deployments found under my-user-name
"bob"
url             inst #    state    age
bob-\<random\>.now.sh   ...
....

But if I try to list deployments for my "bob" application:
>$now ls bob
0 deployments
$now ls \\"bob\\"
x deployments  ...
bob-\<random\>.now.sh

## Cause:
Because of the previously mentioned bug, Docker does not strip the quotes from the Dockerfile command `LABEL name="bob"`

## Solution:
Partial solution until the Docker bug is fixed is to remove the quotes from single word folder names.
Full solution would be to pass through the now.json file, which would allow me to set whatever name I want, in addition to aliases and ENV variables, but alas, this doesn't currently work.

Win10
now version 7.0.1
meteor-now version: ??? (--version doesn't work)

**Comment by jkrup** [comment]
Deprecating in favor of [meteor-hero](https://github.com/jkrup/meteor-hero/).
