### ISSUE TITLE
Does it run forever?

### ISSUE THREAD

**Issue by trusktr** [jkrup/meteor-now#67]
So this does it for free, and it is hosted forever on Zeit Now?

How is this possible? What if I publish hundreds of small example Meteor apps? What if those apps only get 1 visitor per year? Will they just use Zeit's resources, and Zeit doesn't care?

**Comment by purplecones** [comment]
Yea it's hosted on now forever for free. The free Zeit plan allows you to only have 3 concurrent instances. You can have unlimited number of deployments. Deployments go to 'sleep' if they don't get any traffic but you can change that behavior with the now scale command. 

-
MJ

**Comment by trusktr** [comment]
Interesting, so it behaves similar to old Meteor subdomains in the sense of sleeping. I wonder what's the latency for someone visiting and waking a sleeping site. I guess I'll just have to try it out!

**Comment by trusktr** [comment]
> 3 concurrent instances

Does that means 3 separate apps? How many users can connect to them on the OSS plan?

**Comment by purplecones** [comment]
It can be 3 different apps that run on on 1 instance each or 1 app that is scaled to 3 instances. Unlimited connections but I believe there are bandwidth limits. Check their pricing page. 

-
MJ

**Comment by HemalR** [comment]
I guess this issue can be closed (not really an issue).

I will point out though, that their free plan = publicly visible source code.

I'm a paying Zeit client, their tools are extremely dev friendly! Their support and question answering promptness are not so great (but I guess they prioritise development). Either way, I would recommend their base plan without hesitation.
