### ISSUE TITLE
Deploy to specific region/cloud zeit options support

### ISSUE THREAD

**Issue by janat08** [jkrup/meteor-now#68]
https://zeit.co/blog/universal-now

https://github.com/zeit/now-cli

I'm trying to get DB and the deployment in the same region.

**Comment by janat08** [comment]
So any plants for supporting zeit-now cloud/region options>?

**Comment by janat08** [comment]
Like having zeit within same area as db would be awesome.

**Comment by DesignMonkey** [comment]
+1 .. meteor now is deploying to San Francisco... that pretty far away when my site should be running in Denmark (central europe) :)

**Comment by janat08** [comment]
This is a bad issue.
