### ISSUE TITLE
Meteor-up never ends

### ISSUE THREAD

**Issue by davigarcas** [jkrup/meteor-now#69]
I'm testing a new site using meteor but when I use meteor-up for some weird reason it doesn't work just says "building meteor app (this can take several minutes" I test other projects with node.js and react.js and works fine just take to upload 30 to 40 seconds .

![screen shot 2017-09-08 at 12 12 06 am](https://user-images.githubusercontent.com/8272941/30197040-bed37bc2-942a-11e7-8e17-4c01b802744f.png)

**Comment by purplecones** [comment]
We pushed a new version of `meteor-now`. Can you update to the latest and try again?

**Comment by davigarcas** [comment]
Thank you, it works
