### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by christophmayrhofer** [jkrup/meteor-now#73]
Could you please add a license for the project

**Comment by StorytellerCZ** [comment]
The license is set as MIT in the `package.json`.

**Comment by christophmayrhofer** [comment]
@StorytellerCZ  Thanks, I was looking for a license.md file in the root. The info in the package.json works fine as well :)

**Comment by purplecones** [comment]
We're working on a complete rewrite (https://github.com/jkrup/meteor-now/pull/75) that should resolve many outstanding issues and will also include a proper license file.
