### ISSUE TITLE
Why don't we use meteor npm install in Step 8?

### ISSUE THREAD

**Issue by vladejs** [jkrup/meteor-now#80]
Looking at the output, the dockerfile uses `npm install`. This leads to a warning at the end of the build:

```
> Note: you are using a pure-JavaScript implementation of bcrypt.
> While this implementation will work correctly, it is known to be
> approximately three times slower than the native implementation.
> In order to use the native implementation instead, run
>   meteor npm install --save bcrypt
> in the root directory of your application.
> Deployment complete!
```

How can you fix this? use meteor's own `npm` binary

**Comment by jkrup** [comment]
I'm not sure that running `meteor npm` vs `npm` would make a difference. The issues seems more to do with the Dockerimage being used not containing certain things (like a specific version of Python) that are required to build a native `bcrypt`. So there may be a way to fix it by passing in the right `--dependencies`

According to https://github.com/kelektiv/node.bcrypt.js#dependencies you need python 2.x, so you could try passing in --dependencies python-2.7  or --dependencies build-essential 

Also, I could be wrong, but I believe the only thing that bcrypt is used for is hashing the password when logging in / creating accounts so 3x slower won't make any noticeable impact. As far as I can tell it's not used when validating sessions (`shasum` is used instead) https://github.com/meteor/meteor/blob/1687537f6ea03312183059fed45f12f350de2f17/packages/accounts-base/accounts_server.js#L822
