### ISSUE TITLE
Get Something went wrong with now

### ISSUE THREAD

**Issue by HaolinWang8** [jkrup/meteor-now#82]
I have this problem when running "meteor-now -d -e MONGO_URL=@****** -e MONGO_OPLOG_URL=@******* --nosplit"

[METEOR-NOW] - clearing build folder 
 [METEOR-NOW] - Building meteor app (this can take several minutes) 
 [METEOR-NOW] - $ meteor build /home/rof/.meteor-now/build --server-only --architecture=os.linux.x86_64
 [METEOR-NOW] - Preparing build 
 [METEOR-NOW] - Deploying build (this can take several minutes) 
 [METEOR-NOW] - Something went wrong with now

**Comment by orozcorp** [comment]
I have the same Issue!

**Comment by purplecones** [comment]
Does the error always happen when you try to deploy or does it sometimes fail like this? Reason is that the `now` cli child process returned an exception which means that `now` is failing to deploy for some reason. If you run `now ls`, do you see your deployment there? If so, what state is it in?

We should add better error handling here.

**Comment by purplecones** [comment]
Also try deploying a very simple meteor app and see if you still get the error.

**Comment by orozcorp** [comment]
If I run now ls I dont see the deployment there.

I can deploy other of my apps

**Comment by HaolinWang8** [comment]
I finally find the solution here. Upgrade your node to v8.8.1 seems like work on me. Hope this will help you.

**Comment by orozcorp** [comment]
I have upgraded to node v 9 but still it doesnt work
meteor-now@0.5.2
now@8.4.0
npm@5.5.1
<img width="682" alt="screen shot 2017-11-08 at 1 15 26 pm" src="https://user-images.githubusercontent.com/9560595/32569502-eb66fb14-c486-11e7-9845-efe836d3f336.png">

**Comment by orozcorp** [comment]
I copied the app files in to a new app. What I saw is a problem with aldeed:Collection2-core  I had to remove it and now it worked.
