### ISSUE TITLE
Error when passing MONGO_URL with replica set

### ISSUE THREAD

**Issue by Gervwyk** [jkrup/meteor-now#83]
anyone know how to set mongo url as env variable using which includes a replica set?
I keep getting `Error: query parameter replicaSet is an incomplete value pair`
my mongo url is set to: 
```
MONGO_URL='mongodb://xxx:xxx@ccc-0.mongodb.net:27017,ccc-1.mongodb.net:27017,ccc-2.mongodb.net:27017/DBNAME?replicaSet=ccc-0&ssl=true&readPreference=primaryPreferred&w=majority&authSource=admin'
```

My deploy command looks like this:
```
meteor-now -e ROOT_URL="https://www.mysite.com" -e MONGO_URL="mongodb://xxx:xxx@ccc-0.mongodb.net:27017,ccc-1.mongodb.net:27017,ccc-2.mongodb.net:27017/DBNAME?replicaSet=ccc-0&ssl=true&readPreference=primaryPreferred&w=majority&authSource=admin"
````

I've tried all versions of " ' ` types but keep up ending with that error in the deployment log..

**Comment by purplecones** [comment]
Try using now secrets:

```now secrets add mongo_url_stg 'mongodb://xxx:xxx@ccc-0.mongodb.net:27017,ccc-1.mongodb.net:27017,ccc-2.mongodb.net:27017/DBNAME?replicaSet=ccc-0&ssl=true&readPreference=primaryPreferred&w=majority&authSource=admin'```

```
meteor-now -e ROOT_URL="https://www.mysite.com" -e MONGO_URL=@mongo_url_stg
```

**Comment by Gervwyk** [comment]
Thanks! This solved my issue. Really great work on this package!!

**Comment by jkrup** [comment]
Glad that worked! Yeah sometimes terminals can act weird when directly typing special characters (like those in mongoURLs), so it's better to use the secrets.

**Comment by roelvan** [comment]
Maybe useful to add this to the readme? Had to search for closed issues to solve my problems. Thanks @purplecones for the solution!
