### ISSUE TITLE
Why there is file size limit issue?

### ISSUE THREAD

**Issue by lesliedoghouse** [jkrup/meteor-now#84]
> Bundle Splitting

The now free tier has a limitation of 1mb per file. As a workaround, we split the final bundle into pieces prior to uploading. If you are on a paid plan, you can turn this off by passing the --nosplit flag like so meteor-now --nosplit.

> Error! Upload failed
> Error! An unexpected error occurred in provider deploy: Error: File size limit exceeded
    at responseError (/snapshot/now-cli/dist/now.js:193:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
> Upload [--------------------] 0% 292.6s (16.61MB) [9 files]

If Bundle Splitting is default, why I still get file size limit issue? Unable to deploy even once.

Please help.

**Comment by purplecones** [comment]
Not sure why it wouldn't be splitting it for you. Can you do this in the terminal and paste the results.

```
$ cd ~/.meteor-now/build
$ ls -la
```

**Comment by lesliedoghouse** [comment]
There is no "build" folder in .meteor-now folder.

After using Node v6, the file limit error gone. But I got new error now:

[METEOR-NOW] - Something went wrong with now

**Comment by jkrup** [comment]
What happens if you run `meteor-now -d`? Also (sorry if this sounds silly) but could you try running your app locally first too with just `meteor` and make sure that that's working?

**Comment by lesliedoghouse** [comment]
@jkrup The app tested working before deploy.

**Comment by lesliedoghouse** [comment]
[METEOR-NOW] - Something went wrong with now

This error is cause by my end or the server end? Please advice.

**Comment by jkrup** [comment]
Hi @lesliedoghouse, I realize it's been a while, but did you ever get this resolved? If you can put the entire output of `meteor-now -d` that may help.
