### ISSUE TITLE
Free Plan impossible to build mobile app?

### ISSUE THREAD

**Issue by lesliedoghouse** [jkrup/meteor-now#87]
Hi all,

As tested, meteor-now generate unique URL on every deploy. So this makes it impossible to have ROOT_URL for mobile app?

I'm using OSS free plan. Please advice, thanks.

Lesz

**Comment by purplecones** [comment]
You can alias the deployment:
```
$ now alias my-app-cbuukpsblf.now.sh my-new-app-url.now.sh
> Assigning alias my-new-app-url to deployment...
> Success! my-new-app-url.now.sh now points to my-app-cbuukpsblf.now.sh! [1s]
```




https://zeit.co/docs/features/aliases

**Comment by lesliedoghouse** [comment]
Thanks for the info. Will try.
