### ISSUE TITLE
[METEOR-NOW] - Something went wrong with now

### ISSUE THREAD

**Issue by alabrazi** [jkrup/meteor-now#92]
I have :
meteor@1.4.2.1
+ now@8.5.4
+ meteor-now@0.5.3
 
in the command line :
meteor-now -e ROOT_URL=http://Awebsite.com
the result : 
✔ [METEOR-NOW] - Building meteor app (this can take several minutes)
⚠[METEOR-NOW] - WARNING: Did not pass a MONGO_URL. Bundling a NON-PRODUCTION version of
 MongoDB with your application. Read about the limitations here: https://git.io/vM72E
⚠[METEOR-NOW] - WARNING: It might take a few minutes for the app to connect to the bund
led MongoDB instance after the deployment has completed.
✔ [METEOR-NOW] - Preparing build
✖ [METEOR-NOW] - Something went wrong with now

With mongdb:
meteor-now -e MONGO_URL=mongodb://<alabrazi>:<apassword>@ds163016.mlab.com:63016/lama-e ROOT_URL=https://mydomain.com -e NODE_ENV=production`
then I press enter nothing happen and I see >

**Comment by Dev1an** [comment]
I'm having the same issue. Is there a more detailed log file somewhere?

**Comment by jkrup** [comment]
try adding the `-d` flag for debug. that should output a lot more information.

**Comment by Dev1an** [comment]
thanks @jkrup, I tried `meteor-now -d` but the only output I get is:
```
ℹ [METEOR-NOW] - clearing build folder 
ℹ [METEOR-NOW] - Building meteor app (this can take several minutes) 
ℹ [METEOR-NOW] - $ meteor build /Users/damiaan/.meteor-now/build --server-only --architecture=os.linux.x86_64
ℹ [METEOR-NOW] - Preparing build 
⚠ [METEOR-NOW] - WARNING: Did not pass a MONGO_URL. Bundling a NON-PRODUCTION version of MongoDB with your application. Read about the limitations here: https://git.io/vM72E 
⚠ [METEOR-NOW] - WARNING: It might take a few minutes for the app to connect to the bundled MongoDB instance after the deployment has completed. 
ℹ [METEOR-NOW] - creating supervisord.conf 
ℹ [METEOR-NOW] - splitting bundle 
ℹ [METEOR-NOW] - Deploying build (this can take several minutes) 
✖ [METEOR-NOW] - Something went wrong with now 
```

**Comment by Dev1an** [comment]
Are you experiencing the same problem or is this something that only me & @alabrazi are experiencing? (I get this error even with the sample application that is created with `meteor create helloworld`)

**Comment by TimHeckel** [comment]
I needed to add a `production.settings.json` with `{}` at the root of my app because I had specified `NODE_ENV=production` (I don't use a `settings.json` file, but meteor-now expected there to be one.)

**Comment by Dev1an** [comment]
But this error also appears when deploying for development/testing and it doesn't go away if a add a `settings.json` file.

**Comment by adamdawkins** [comment]
Thanks @TimHeckel, that was exactly my issue. Seems like something that could quite easily be flagged, I'd never have found it!

**Comment by janat08** [comment]
Same here tried specifying node dev environment along with development settings json, didn't work.

**Comment by jkrup** [comment]
I'll try to merge in #94 quickly which will provide more detailed logging.

Also created a separate issue #96 to help address the no `production.settings.json` file.
