### ISSUE TITLE
✖ [METEOR-NOW] - Something went wrong with now TypeError: Object.entries is not a function

### ISSUE THREAD

**Issue by NetoDevel** [jkrup/meteor-now#99]
**Command:**
` meteor-now -e MONGO_URL=mongodb://**:**@ds249418.mlab.com:49418/trueblue -e NODE_ENV=production`

**output:**
✔ [METEOR-NOW] - Building meteor app (this can take several minutes)
✔ [METEOR-NOW] - Preparing build
⢀⠀ [METEOR-NOW] - Deploying build (this can take several minutes) args are  { _: [ '/usr/local/bin/node', '/usr/local/bin/meteor-now' ],
  help: false,
  version: false,
  e:
   [ 'MONGO_URL=mongodb://**:**@ds249418.mlab.com:49418/trueblue',
     'NODE_ENV=production' ],
  '$0': 'meteor-now' }
✖ [METEOR-NOW] - Something went wrong with now TypeError: Object.entries is not a function

**Comment by jkrup** [comment]
Hi, if you're still having this problem, could you try passing the `-d` command?

**Comment by sudotong** [comment]
I had to upgrade my local version of node (originally was 6.10.3) using `nvm` to solve this issue. I went to 9.3.0 which let me get past this issue
